-- MySQL Script generated by MySQL Workbench
-- seg 25 ago 2025 14:39:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_pokemon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_pokemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_pokemon` ;
USE `banco_pokemon` ;

-- -----------------------------------------------------
-- Table `banco_pokemon`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`pokemon` (
  `idpokemon` INT NOT NULL AUTO_INCREMENT,
  `national` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `gen` INT NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idpokemon`),
  UNIQUE INDEX `idpokemon_UNIQUE` (`idpokemon` ASC) VISIBLE,
  UNIQUE INDEX `national_UNIQUE` (`national` ASC) VISIBLE,
  UNIQUE INDEX `imagem_UNIQUE` (`imagem` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_pokemon`.`stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`stats` (
  `idstats` INT NOT NULL AUTO_INCREMENT,
  `hp` INT NOT NULL,
  `attack` INT NOT NULL,
  `defense` INT NOT NULL,
  `sp_attack` INT NOT NULL,
  `sp_defense` INT NOT NULL,
  `speed` INT NOT NULL,
  `idpokemon` INT NOT NULL,
  PRIMARY KEY (`idstats`),
  UNIQUE INDEX `idstats_UNIQUE` (`idstats` ASC) VISIBLE,
  INDEX `fk_stats_pokemon1_idx` (`idpokemon` ASC) VISIBLE,
  CONSTRAINT `fk_stats_pokemon1`
    FOREIGN KEY (`idpokemon`)
    REFERENCES `banco_pokemon`.`pokemon` (`idpokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_pokemon`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`types` (
  `idtypes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtypes`),
  UNIQUE INDEX `idtypes_UNIQUE` (`idtypes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_pokemon`.`build`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`build` (
  `idbuild` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idpokemon` INT NOT NULL,
  PRIMARY KEY (`idbuild`),
  UNIQUE INDEX `idbuild_UNIQUE` (`idbuild` ASC) VISIBLE,
  INDEX `fk_build_pokemon1_idx` (`idpokemon` ASC) VISIBLE,
  CONSTRAINT `fk_build_pokemon1`
    FOREIGN KEY (`idpokemon`)
    REFERENCES `banco_pokemon`.`pokemon` (`idpokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_pokemon`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `Tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_pokemon`.`pokemon_has_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`pokemon_has_types` (
  `idpokemon` INT NOT NULL,
  `idtypes` INT NOT NULL,
  PRIMARY KEY (`idpokemon`, `idtypes`),
  INDEX `fk_pokemon_has_types_types1_idx` (`idtypes` ASC) VISIBLE,
  INDEX `fk_pokemon_has_types_pokemon_idx` (`idpokemon` ASC) VISIBLE,
  CONSTRAINT `fk_pokemon_has_types_pokemon`
    FOREIGN KEY (`idpokemon`)
    REFERENCES `banco_pokemon`.`pokemon` (`idpokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_has_types_types1`
    FOREIGN KEY (`idtypes`)
    REFERENCES `banco_pokemon`.`types` (`idtypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_pokemon`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pokemon_fav` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idperfil`),
  UNIQUE INDEX `idperfil_UNIQUE` (`idperfil` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_perfil_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `banco_pokemon`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_pokemon`.`suporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`suporte` (
  `idsuporte` INT NOT NULL AUTO_INCREMENT,
  `reclamacao` VARCHAR(150) NULL,
  `sugestao` VARCHAR(150) NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idsuporte`),
  UNIQUE INDEX `idsuporte_UNIQUE` (`idsuporte` ASC) VISIBLE,
  INDEX `fk_suporte_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_suporte_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `banco_pokemon`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_pokemon`.`treinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_pokemon`.`treinador` (
  `idtreinador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `idade` INT NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(100) NULL,
  `regiao` VARCHAR(100) NULL,
  `time_atual` TEXT NULL,
  `data_cadastro` DATE NOT NULL,
  `idpokemon` INT NOT NULL,
  PRIMARY KEY (`idtreinador`),
  UNIQUE INDEX `idtreinador_UNIQUE` (`idtreinador` ASC) VISIBLE,
  INDEX `fk_treinador_pokemon1_idx` (`idpokemon` ASC) VISIBLE,
  CONSTRAINT `fk_treinador_pokemon1`
    FOREIGN KEY (`idpokemon`)
    REFERENCES `banco_pokemon`.`pokemon` (`idpokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
