-- MySQL Script generated by MySQL Workbench
-- ter 20 mai 2025 11:13:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pokemon` (
  `idpokemon` INT(11) NOT NULL AUTO_INCREMENT,
  `national` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `gen` INT(11) NOT NULL,
  PRIMARY KEY (`idpokemon`),
  UNIQUE INDEX `idpokemon_UNIQUE` (`idpokemon` ASC) VISIBLE,
  UNIQUE INDEX `national_UNIQUE` (`national` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 155
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`build`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`build` (
  `idbuild` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idpokemon` INT(11) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idbuild`),
  UNIQUE INDEX `idbuild_UNIQUE` (`idbuild` ASC) VISIBLE,
  INDEX `fk_build_pokemon1_idx` (`idpokemon` ASC) VISIBLE,
  INDEX `fk_build_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_build_pokemon1`
    FOREIGN KEY (`idpokemon`)
    REFERENCES `mydb`.`pokemon` (`idpokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_build_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `idperfil` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_exibicao` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `idusuario` INT(11) NOT NULL,
  `favorito_idpokemon` INT(11) NULL,
  PRIMARY KEY (`idperfil`),
  UNIQUE INDEX `idperfil_UNIQUE` (`idperfil` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome_exibicao` ASC) VISIBLE,
  INDEX `fk_perfil_usuario1_idx` (`idusuario` ASC) VISIBLE,
  INDEX `fk_perfil_pokemon1_idx` (`favorito_idpokemon` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_pokemon1`
    FOREIGN KEY (`favorito_idpokemon`)
    REFERENCES `mydb`.`pokemon` (`idpokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`types` (
  `idtypes` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtypes`),
  UNIQUE INDEX `idtypes_UNIQUE` (`idtypes` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pokemon_has_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pokemon_has_types` (
  `idpokemon` INT(11) NOT NULL,
  `idtypes` INT(11) NOT NULL,
  PRIMARY KEY (`idpokemon`, `idtypes`),
  INDEX `fk_pokemon_has_types_types1_idx` (`idtypes` ASC) VISIBLE,
  INDEX `fk_pokemon_has_types_pokemon_idx` (`idpokemon` ASC) VISIBLE,
  CONSTRAINT `fk_pokemon_has_types_pokemon`
    FOREIGN KEY (`idpokemon`)
    REFERENCES `mydb`.`pokemon` (`idpokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_has_types_types1`
    FOREIGN KEY (`idtypes`)
    REFERENCES `mydb`.`types` (`idtypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stats` (
  `idstats` INT(11) NOT NULL AUTO_INCREMENT,
  `hp` INT(11) NOT NULL,
  `attack` INT(11) NOT NULL,
  `defense` INT(11) NOT NULL,
  `sp_attack` INT(11) NOT NULL,
  `sp_defense` INT(11) NOT NULL,
  `speed` INT(11) NOT NULL,
  `idpokemon` INT(11) NOT NULL,
  PRIMARY KEY (`idstats`),
  UNIQUE INDEX `idstats_UNIQUE` (`idstats` ASC) VISIBLE,
  INDEX `fk_stats_pokemon1_idx` (`idpokemon` ASC) VISIBLE,
  CONSTRAINT `fk_stats_pokemon1`
    FOREIGN KEY (`idpokemon`)
    REFERENCES `mydb`.`pokemon` (`idpokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 162
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`suporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suporte` (
  `idsuporte` INT(11) NOT NULL AUTO_INCREMENT,
  `reclamacao` VARCHAR(150) NULL DEFAULT NULL,
  `sugestao` VARCHAR(150) NULL DEFAULT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idsuporte`),
  UNIQUE INDEX `idsuporte_UNIQUE` (`idsuporte` ASC) VISIBLE,
  INDEX `fk_suporte_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_suporte_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
